Add initial benchmark and controls for OCI Thrifty. Closes #1
turbot/steampipe-mod-oci-thrifty pull request #2
Opened 2021-07-22 09:46 UTC by khushboo9024

2021-07-22 11:57 UTC, rajlearner17 commented on controls/core.sp
> +  title         = "Core instances with low CPU utilization should be reviewed"
Compute instances with low CPU utilization should be reviewed

2021-07-22 11:58 UTC, rajlearner17 commented on controls/core.sp
> +  title       = "Long running instances should be reviewed"
Long running compute instances should be reviewed

2021-07-22 12:07 UTC, rajlearner17 commented on controls/core.sp
> +  title       = "Block volume should be enabled with auto-tune for performance"
Block volume should be enabled with auto-tune for better performance

2021-07-22 12:17 UTC, rajlearner17 commented on controls/database.sp
> +  title         = "Database Checks"
This will be under Oracle Database i.e.
Database > Oracle Database Checks

2021-07-22 16:02 UTC, Subhajit97 approved these changes

2021-07-22 16:10 UTC, rajlearner17 approved these changes
LGTM

2021-07-27 18:16 UTC, cbruno10 requested changes
@Subhajit97 Please see comments, thanks!

2021-07-27 18:16 UTC, cbruno10 commented on controls/mysql.sp
> +  description = "MySQL DB systems created over 90 days ago should be reviewed and deleted if not required."
If there aren't any equivalent settings for reserved instances, or another cost saving measure for long running instances, I think we should remove this control. Having a DB system running for 90 days ago or more alone isn't enough to recommend a deletion.

2021-07-27 18:16 UTC, cbruno10 commented on controls/database.sp
> +  title       = "Autonomous database created over 90 days ago should be reviewed"
If there aren't any equivalent settings for reserved instances, or another cost saving measure for long running instances, I think we should remove this control. Having an autonomous database running for 90 days ago or more alone isn't enough to recommend a deletion.

2021-07-27 18:16 UTC, cbruno10 commented on controls/core.sp
> +locals {
@Subhajit97 Can you please try renaming this benchmark and its controls from core->compute and see how that looks in the hub site? Core is the TF + table name scheme we use, but Compute seems to be more common in OCI's docs, so I'm interested to see if this one is more recognizable for users.

2021-07-27 18:16 UTC, cbruno10 commented on controls/core.sp
> +      a.display_name || ' created at ' || a.time_created || '.' as reason,
For this reason, and others in this benchmark (or others), can we also include the `(num_days)` as well?

2021-07-31 15:41 UTC, cbruno10 approved these changes

2021-07-31 15:42 UTC, merged